apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: development
spec:
  type: team
  profile:
    displayName: Development Team
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=DevTeam
  parent: default-org
  members:
    - samdudgeoncap
